In [1]:
import pandas as pd

df = pd.read_csv('/Users/sihyun/Desktop/github/SeSAC_DE/sesac_workspace_mac/python/복습/seoul_park.csv')

In [2]:
print(df)

              날짜 공휴일     날씨   유료합계     어른  청소년  어린이  외국인   단체   무료합계     총계
0     2016-01-01   O  구름 조금  3,359  2,799  141  419   47    0  1,023  4,382
1     2016-01-02   O  구름 많음  5,173  4,370  203  600  100  111  2,092  7,265
2     2016-01-03   O  구름 많음  3,008  2,571  128  309   91    0  1,549  4,557
3     2016-01-04   X  구름 많음    890    602  NaN  235   51  223    800  1,690
4     2016-01-05   X  구름 많음    416    319   35   62   43   47    840  1,256
...          ...  ..    ...    ...    ...  ...  ...  ...  ...    ...    ...
1081  2019-03-27   X  구름 많음    504    464   10   30   21    -    613  1,117
1082  2019-03-28   X  구름 많음    761    687   46   28   35  108    904  1,665
1083  2019-03-29   X  구름 조금  1,644  1,447  120   77   14  188  1,226  2,870
1084  2019-03-30   O     흐림  1,539  1,326   44  169   29  115    913  2,452
1085  2019-03-31   O  구름 조금  3,061  2,563  111  387   53    -  1,357  4,418

[1086 rows x 11 columns]

In [4]:
df.shape

(1086, 11)

In [5]:
df.columns

Index(['날짜', '공휴일', '날씨', '유료합계', '어른', '청소년', '어린이', '외국인', '단체', '무료합계',
       '총계'],
      dtype='object')

In [7]:
df.dtypes

날짜      object
공휴일     object
날씨      object
유료합계    object
어른      object
청소년     object
어린이     object
외국인     object
단체      object
무료합계    object
총계      object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086 entries, 0 to 1085
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      1086 non-null   object
 1   공휴일     1086 non-null   object
 2   날씨      946 non-null    object
 3   유료합계    1086 non-null   object
 4   어른      1086 non-null   object
 5   청소년     1081 non-null   object
 6   어린이     1086 non-null   object
 7   외국인     1086 non-null   object
 8   단체      1086 non-null   object
 9   무료합계    1086 non-null   object
 10  총계      1086 non-null   object
dtypes: object(11)
memory usage: 93.5+ KB

In [10]:
df.describe()

,날짜,공휴일,날씨,유료합계,어른,청소년,어린이,외국인,단체,무료합계,총계
count,1086,1086,946,1086,1086,1081,1086,1086,1086,1086,1086
unique,1086,2,7,996,941,474,603,247,522,906,1012
top,2016-01-01,X,구름 많음,213,198,14,10,13,0,837,996
freq,1,731,277,5,4,17,11,22,351,5,3

In [11]:
df.head()

           날짜 공휴일     날씨   유료합계     어른  청소년  어린이  외국인   단체   무료합계     총계
0  2016-01-01   O  구름 조금  3,359  2,799  141  419   47    0  1,023  4,382
1  2016-01-02   O  구름 많음  5,173  4,370  203  600  100  111  2,092  7,265
2  2016-01-03   O  구름 많음  3,008  2,571  128  309   91    0  1,549  4,557
3  2016-01-04   X  구름 많음    890    602  NaN  235   51  223    800  1,690
4  2016-01-05   X  구름 많음    416    319   35   62   43   47    840  1,256

In [12]:
df.tail()

              날짜 공휴일     날씨   유료합계     어른  청소년  어린이 외국인   단체   무료합계     총계
1081  2019-03-27   X  구름 많음    504    464   10   30  21    -    613  1,117
1082  2019-03-28   X  구름 많음    761    687   46   28  35  108    904  1,665
1083  2019-03-29   X  구름 조금  1,644  1,447  120   77  14  188  1,226  2,870
1084  2019-03-30   O     흐림  1,539  1,326   44  169  29  115    913  2,452
1085  2019-03-31   O  구름 조금  3,061  2,563  111  387  53    -  1,357  4,418

In [14]:
df2 = df['날씨']

In [16]:
print(df2)
df2.info()

0       구름 조금
1       구름 많음
2       구름 많음
3       구름 많음
4       구름 많음
        ...
1081    구름 많음
1082    구름 많음
1083    구름 조금
1084       흐림
1085    구름 조금
Name: 날씨, Length: 1086, dtype: object
<class 'pandas.core.series.Series'>
RangeIndex: 1086 entries, 0 to 1085
Series name: 날씨
Non-Null Count  Dtype
--------------  -----
946 non-null    object
dtypes: object(1)
memory usage: 8.6+ KB

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086 entries, 0 to 1085
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      1086 non-null   object
 1   공휴일     1086 non-null   object
 2   날씨      946 non-null    object
 3   유료합계    1086 non-null   object
 4   어른      1086 non-null   object
 5   청소년     1081 non-null   object
 6   어린이     1086 non-null   object
 7   외국인     1086 non-null   object
 8   단체      1086 non-null   object
 9   무료합계    1086 non-null   object
 10  총계      1086 non-null   object
dtypes: object(11)
memory usage: 93.5+ KB

In [26]:
df["날씨","총계"]

KeyError: ('날씨', '총계')